const fighters=[{name:"KEITHLOCKS",tag:"THE SHOWMAN",img:"assets/keithlocks.jpg",power:88,speed:84,wrestling:76,defense:80},{name:"MAKOTOJAY",tag:"THE TECHNICIAN",img:"assets/makotojay.jpg",power:78,speed:82,wrestling:86,defense:84},{name:"FARGOFORCE",tag:"THE PRESSURE",img:"assets/fargoforce.jpg",power:84,speed:72,wrestling:91,defense:77},{name:"SCAPEGOATIE",tag:"THE WILDCARD",img:"assets/scapegoatie.jpg",power:92,speed:68,wrestling:73,defense:70}];
const $=id=>document.getElementById(id);let selected=null,opponent=null,pHp=100,aHp=100,pStam=100,aStam=100,seconds=60,round=1,timer=null,locked=false;
function show(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active")}
function render(){$("roster").innerHTML=fighters.map((f,i)=>`<article class="card" data-i="${i}"><img src="${f.img}" alt="${f.name}"><div class="shade"></div><div class="card-info"><div class="tag">${f.tag}</div><h3>${f.name}</h3><div class="stats"><span class="stat">PWR ${f.power}</span><span class="stat">SPD ${f.speed}</span><span class="stat">WRS ${f.wrestling}</span><span class="stat">DEF ${f.defense}</span></div></div></article>`).join("");document.querySelectorAll(".card").forEach(c=>c.addEventListener("click",()=>pick(+c.dataset.i)))}
function pick(i){const f=fighters[i];if(!selected){selected=f;document.querySelector(`[data-i="${i}"]`).classList.add("selected");$("selectionStatus").textContent=`${f.name} selected — now choose an opponent`;return}if(f===selected){selected=null;document.querySelector(`[data-i="${i}"]`).classList.remove("selected");$("selectionStatus").textContent="Choose your fighter";$("fightBtn").disabled=true;return}opponent=f;document.querySelectorAll(".card").forEach(c=>c.classList.remove("opponent"));document.querySelector(`[data-i="${i}"]`).classList.add("opponent");$("selectionStatus").textContent=`${selected.name} vs ${opponent.name}`;$("fightBtn").disabled=false}
$("fightBtn").onclick=start;
function start(){if(!selected||!opponent)return;pHp=aHp=pStam=aStam=100;seconds=60;round=1;locked=false;$("pName").textContent=selected.name;$("aName").textContent=opponent.name;$("pSprite img").src=selected.img;$("aSprite img").src=opponent.img;$("round").textContent="R1";$("fightMessage").textContent="FIGHT!";show("fight");update();clearInterval(timer);timer=setInterval(tick,1000)}
function tick(){if(locked)return;seconds--;if(seconds%3===0)ai();if(seconds<=0){seconds=60;round++;if(round>3){finish(pHp>=aHp);return}$("round").textContent="R"+round;pStam=Math.min(100,pStam+22);aStam=Math.min(100,aStam+22)}pStam=Math.min(100,pStam+1);aStam=Math.min(100,aStam+1);update()}
function update(){$("pHp").style.width=Math.max(0,pHp)+"%";$("aHp").style.width=Math.max(0,aHp)+"%";$("pHpText").textContent=Math.round(Math.max(0,pHp));$("aHpText").textContent=Math.round(Math.max(0,aHp));$("pStam").style.width=pStam+"%";$("aStam").style.width=aStam+"%";$("timer").textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,"0")}`}
const cost={jab:6,cross:8,kick:11,block:2,takedown:14,heavy:21};
function player(action){if(locked)return;if(["left","right","forward"].includes(action)){move(action);return}if(pStam<cost[action]){msg("LOW STAMINA");return}pStam-=cost[action];locked=true;const s=$("pSprite");s.classList.add(action==="block"?"block":"attack");let dmg=0,r=Math.random();if(action==="jab")dmg=5+selected.speed/34;if(action==="cross")dmg=8+selected.power/27;if(action==="kick")dmg=9+selected.power/24;if(action==="heavy")dmg=14+selected.power/17;if(action==="takedown")dmg=7+selected.wrestling/11;if(r<.13&&action!=="block")dmg*=.35;aHp=Math.max(0,aHp-dmg);if(dmg>3)impact(dmg>12?"BIG HIT!":"HIT!");setTimeout(()=>{s.classList.remove("attack","block");locked=false;update();if(aHp<=0)finish(true)},180)}
function move(dir){const s=$("pSprite");const n=dir==="left"?-18:dir==="right"?18:5;s.style.transform=`translateX(${n}px)`;setTimeout(()=>s.style.transform="",160)}
function ai(){if(locked||aHp<=0)return;const moves=["jab","cross","kick","heavy","takedown","block"],m=moves[Math.floor(Math.random()*moves.length)];if(aStam<cost[m])return;aStam-=cost[m];const s=$("aSprite");s.classList.add(m==="block"?"block":"attack");let dmg=m==="block"?0:m==="jab"?5+opponent.speed/37:m==="cross"?8+opponent.power/30:m==="kick"?9+opponent.power/27:m==="heavy"?13+opponent.power/20:7+opponent.wrestling/12;dmg*=Math.max(.25,1-selected.defense/180);pHp=Math.max(0,pHp-dmg);if(dmg>4)impact(dmg>11?"OUCH!":"HIT!");setTimeout(()=>{s.classList.remove("attack","block");update();if(pHp<=0)finish(false)},180)}
function impact(t){$("hitText").textContent=t;$("hitText").classList.remove("show");void $("hitText").offsetWidth;$("hitText").classList.add("show")}
function msg(t){$("fightMessage").textContent=t;setTimeout(()=>{$("fightMessage").textContent="FIGHT!"},500)}
function finish(win){if(locked)return;locked=true;clearInterval(timer);show("result");const w=win?selected:opponent;$("resultTitle").textContent=win?"VICTORY":"DEFEAT";$("resultCard").innerHTML=`<div class="kicker">WINNER</div><div class="winner">${w.name}</div><p>${w.tag}</p><p>${selected.name}: ${Math.round(pHp)} HP • ${opponent.name}: ${Math.round(aHp)} HP</p>`}
document.querySelectorAll("[data-action]").forEach(b=>{const act=b.dataset.action;b.addEventListener("pointerdown",e=>{e.preventDefault();player(act)})});window.addEventListener("keydown",e=>{if(e.repeat)return;const k=e.key.toLowerCase(),map={a:"left",d:"right",w:"forward",arrowleft:"left",arrowright:"right",arrowup:"forward",j:"jab",k:"cross",l:"kick",i:"block",o:"takedown",p:"heavy"};if(map[k]){e.preventDefault();player(map[k])}});$("backBtn").onclick=()=>{clearInterval(timer);selected=null;opponent=null;render();$("fightBtn").disabled=true;$("selectionStatus").textContent="Choose your fighter";show("select")};$("rematchBtn").onclick=start;$("rosterBtn").onclick=()=>$("backBtn").click();render();